create table connection
(
    id               int8 generated by default as identity,
    disconnect_until timestamp,
    room_id          int8,
    user_id          int8,
    primary key (id)
);
create table message
(
    id            int8 generated by default as identity,
    send_time     timestamp,
    text          varchar(255),
    connection_id int8,
    primary key (id)
);
create table room
(
    id       int8 generated by default as identity,
    name     varchar(255),
    type     varchar(255),
    owner_id int8,
    primary key (id)
);
create table users
(
    id           int8 generated by default as identity,
    banned_until timestamp,
    name         varchar(255),
    password     varchar(255),
    role         varchar(255),
    primary key (id)
);


alter table if exists connection
    add constraint fk_room_id foreign key (room_id) references room;
alter table if exists connection
    add constraint fk_user_id foreign key (user_id) references users;
alter table if exists message
    add constraint fk_room_id foreign key (connection_id) references connection;
alter table if exists room
    add constraint fk_user_id foreign key (owner_id) references users;